# Generated by Django 6.0.4 on 2026-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_requirements_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='met_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
