# Generated by Django 6.0.4 on 2026-05-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_application_met_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GetGig', max_length=100)),
                ('hero_title', models.CharField(default='Find the perfect talent for your next big idea.', max_length=255)),
                ('hero_subtitle', models.TextField(default='A premium marketplace for high-end freelancers.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_assets/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
