# Generated by Django 6.0.5 on 2026-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_assets/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Post premium gigs, match with qualified freelancers, and manage proposals all in one place.'),
        ),
    ]
