# Generated by Django 6.0.5 on 2026-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed Early'), ('ended', 'Ended')], default='active', max_length=20),
        ),
    ]
