"""
Django settings for getgig project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# SECURITY & ENVIRONMENT CONFIGURATION
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-m&d3^8v$51_9c!r0_f#k+u(z)w@q=e7xb2p%o*jla-n6h4s')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_ENV = os.environ.get('DJANGO_DEBUG')
if DEBUG_ENV is None:
    DEBUG = True
else:
    DEBUG = DEBUG_ENV == 'True'

# Allow Vercel URLs and local development environments
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,.vercel.app').split(',')


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',  # Primary storage handler component
    'cloudinary',
    'users',
    'projects',
    'storages',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Must stay directly under SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'getgig.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'getgig.wsgi.application'


# ==============================================================================
# DATABASES (Local SQLite fallback / Production Supabase Postgres)
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600, 
        ssl_require=True
    )


# ==============================================================================
# STATIC & MEDIA FILES CONFIGURATION (WhiteNoise & Cloudinary Managed)
# ==============================================================================

STATIC_URL = '/static/'

# Where collectstatic dumps files. Vercel routes expect assets to live in 'static'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Enables WhiteNoise compression and caching for production environments
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media assets fallback engine mapping configurations
MEDIA_URL = '/media/'

# Apply provided production credentials fallback string directly
CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': os.environ.get(
        'CLOUDINARY_URL', 
        'cloudinary://813553949787683:6ACOViZygV8ewifaBo4_LMbjC8s@djmjge5xu'
    )
}

# Auto-detect Cloudinary state hook execution loop
if os.environ.get('CLOUDINARY_URL') or CLOUDINARY_STORAGE['CLOUDINARY_URL']:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==============================================================================
# AUTHENTICATION & CORE POLICIES
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = 'users:dashboard_redirect'
LOGOUT_REDIRECT_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ==============================================================================
# PROGRESSIVE WEB APP (PWA) CONFIGURATION
# ==============================================================================

PWA_APP_NAME = 'GetGig'
PWA_APP_DESCRIPTION = "Social Freelancing Marketplace"
PWA_APP_THEME_COLOR = '#0C6FBD'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/logo.jpg',
        'sizes': '160x160'
    },
    {
        'src': '/static/images/logo.jpg',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'